services:
  gpt-sovits-api-v2-cpu:
    build:
      context: .
      dockerfile: Dockerfile.api-v2
    container_name: gpt-sovits-api-v2-cpu
    ports:
      - "9880:9880"
    volumes:
      # Mount the SoVITS model (e8_s224)
      - /DockerConfig/gpt-sovitts/models/vits/lisa_test_e8_s224.pth:/app/GPT_SoVITS/pretrained_models/s2G488k.pth:ro
      # Mount the GPT model (e15)
      - /DockerConfig/gpt-sovitts/models/gpt/lisa_test-e15.ckpt:/app/GPT_SoVITS/pretrained_models/s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt:ro
      # Mount configuration file as writable
      - /DockerConfig/gpt-sovitts/models/tts_infer_minimal.yaml:/app/GPT_SoVITS/configs/tts_infer.yaml
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9880/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # gpt-sovits-api-v2-gpu:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.api-v2-gpu
  #   container_name: gpt-sovits-api-v2-gpu
  #   ports:
  #     - "9881:9880"  # Different port to avoid conflict
  #   volumes:
  #     # Mount the SoVITS model (e8_s224)
  #     - ./models/pretrained_models/lisa_test_e8_s224.pth:/app/GPT_SoVITS/pretrained_models/s2G488k.pth:ro
  #     # Mount the GPT model (e15)
  #     - ./models/pretrained_models/lisa_test-e15.ckpt:/app/GPT_SoVITS/pretrained_models/s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt:ro
  #     # Mount configuration file if you want to customize it
  #     - ./GPT_SoVITS/configs/tts_infer.yaml:/app/GPT_SoVITS/configs/tts_infer.yaml:ro
  #   environment:
  #     - PYTHONPATH=/app
  #     - PYTHONUNBUFFERED=1
  #     - CUDA_VISIBLE_DEVICES=0
  #   runtime: nvidia
  #   shm_size: "8g"
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9880/docs"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 60s
  #   profiles:
  #     - gpu

networks:
  default:
    name: gpt-sovits-network